version: '3.7'
services:
  exposure_sites:
    image: ghcr.io/codingric/exposure_sites
    build: src/notifier
    environment:
      - TOKEN

  trivy:
    image: ghcr.io/aquasecurity/trivy:latest
    command: |
      -q image --exit-code 1 -s HIGH ghcr.io/codingric/exposure_sites:latest

  checkov:
    image: bridgecrew/checkov:latest
    command: '-d /src'
    volumes:
      - ./src/notifier:/src

  tests:
    image: golang:alpine
    working_dir: /app
    volumes:
      - ./src/notifier:/app
    entrypoint: |
      sh -c 'apk add gcc libc-dev && go mod download && go test -v -cover'