apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: exposure-sites
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: exposure-sites
              image: ghcr.io/codingric/exposure_sites
              imagePullPolicy: Always
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: exposure-sites
                      key: token
          restartPolicy: OnFailure
