name: Build docker image

on: [push]

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: docker-compose run tests

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: codingric
          password: ${{ secrets.GHCR_PAT }}

      - name: Build docker image
        run: |
          docker buildx create --use \
          && docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t ghcr.io/codingric/exposure_sites --push notifier

      - name: Static scans
        run: docker-compose run scan
